library(org.Mm.eg.db)
source("./utils/enrichissement.R")
tableau = read.csv("./Example_files/filtered_data.csv",sep = ",")
tableau %>% head()
table_filtered = tableau %>% independent_filtering()
ids = conversion_table(table_filtered,from = "ENSEMBL","ENTREZID",organism_db = "org.Mm.eg.db")
table_filtered_new_ids = convert_results_ids(results = table_filtered,ids)

ora_ids = prepare_ora(table_filtered_new_ids[table_filtered_new_ids$diff_expressed != "NO_DE",])
gsea_ids = prepare_gsea(table_filtered_new_ids)
universe = prepare_universe(table_filtered_new_ids)

gsea_go = load_gsea_GO_enrichment(gsea_ids,organism_db = "org.Mm.eg.db",ont = "ALL",key_type = "ENTREZID")
ora_go = load_ora_go(ora_ids,universe,"org.Mm.eg.db","ENTREZID","MF")
gsea_kegg = load_gsea_kegg_enrichment(gsea_ids,"mmu","ncbi-geneid",pvalue_cutoff = 1)
ora_kegg = load_ora_kegg(gene_list = ora_ids,organism_db = "mmu",key_type = "ncbi-geneid",universe = universe)
ora_kegg_after_filter = filter_table_enrich_results(ora_kegg,p_value_cutoff = 0.2,0.3,0.3)
ora_kegg_after_filter %>% draw_cnetplot()
ora_go_after_filter = filter_table_enrich_results(ora_go,0.2,0.5,0.5)
ora_go_after_filter %>% draw_dotplot()
ora_go_after_filter
ora_kegg@result %>% head()
gsea_kegg@result %>% head()
gsea_kegg %>% enrichplot::dotplot()
