library(org.Mm.eg.db)
source("./utils/enrichissement.R")
tableau = read.csv("./Example_files/filtered_data.csv",sep = ",")
tableau %>% head()
table_filtered = tableau %>% independent_filtering()
ids = conversion_table(table_filtered$ID,from = "ENSEMBL",organism_db = "org.Mm.eg.db")

table_filtered_new_ids = convert_results_ids(table_filtered,ids)

ora_ids = prepare_ora(table_filtered_new_ids)
gsea_ids = prepare_gsea(table_filtered_new_ids,metric = "pval")
universe = prepare_universe(tableau)

gsea_go = load_gsea_GO_enrichment(gsea_ids,organism_db = "org.Mm.eg.db")
ora_go = load_ora_go(ora_ids,universe,"org.Mm.eg.db")
gsea_kegg = load_gsea_kegg_enrichment(gsea_ids,"mmu")
ora_kegg = load_ora_kegg(gene_list = ora_ids,organism_db = "mmu",universe = universe)
ora_kegg_after_filter = filter_table_enrich_results(ora_kegg,p_value_cutoff = 0.2,0.3,0.3)
ora_kegg_after_filter %>% draw_cnetplot()
ora_go_after_filter = filter_table_enrich_results(ora_go,0.2,0.5,0.5)
ora_go_after_filter@result$ONTOLOGY %>% unique()
a = filter_go_enrich_results(ora_go_after_filter,ontology = c("MF","CC"))
ora_go_after_filter %>% draw_dotplot(show_category = 30)
ora_kegg@result %>% head()
gsea_kegg@result %>% head()
gsea_kegg %>% enrichplot::dotplot()
